-- The CHECK constraints that used to live here are now part of the initial
-- migration (prisma/migrations/…_init/migration.sql), so `prisma migrate deploy`
-- applies them and a fresh database cannot come up without them.
--
-- They were moved because keeping them here did not work. This file was a
-- manual post-migrate step, and products_slot_range spent the whole of that
-- period silently NOT APPLIED — it referenced sort_order, while @@map renames
-- tables and leaves column names camelCase. The ALTER errored, psql moved on to
-- the next statement, and the five-slot cap that the README and schema.prisma
-- both advertise as a database guarantee simply was not there.
--
-- Add new constraints as a new migration, never here.
-- src/lib/constraints.db.test.ts asserts they are present, so a migration that
-- drops one fails CI rather than failing quietly in production.


-- ─────────────────────────────────────────────────────────────────────────
-- Deployment step, NOT a migration.
--
-- The audit log is append-only. Prisma has no way to express this and a
-- migration cannot know the role name your DATABASE_URL connects as, so run
-- this by hand once per environment, substituting that role:
--
--   REVOKE UPDATE, DELETE ON admin_audit_log FROM app_user;
--
-- src/lib/audit.ts deliberately exposes no update or delete helper, but that is
-- a convention. This is the enforcement. A rewritable record of admin actions
-- is worthless in exactly the situation you would need it.
-- ─────────────────────────────────────────────────────────────────────────
